[theme]
base = "dark"
primaryColor = "#B6A0FF"
backgroundColor = "#0B0E13"
secondaryBackgroundColor = "#151923"
textColor = "#F4F5F0"
linkColor = "#C4B6FF"
borderColor = "#303343"
dataframeHeaderBackgroundColor = "#202534"
showWidgetBorder = true
baseRadius = "medium"
buttonRadius = "medium"
chartCategoricalColors = ["#B6A0FF", "#D7FF42", "#FF725C", "#67CEDA", "#718096"]

[theme.sidebar]
backgroundColor = "#10131B"
secondaryBackgroundColor = "#1C2130"
primaryColor = "#D7FF42"
